최근 검색어 저장 구현
ADAM-2022/Module-MeetUp pull request #20
Opened 2022-09-25 10:31 UTC by TaekH

### Motivation 🥳 (코드를 추가/변경하게 된 이유)
게시글 검색창에서 최근에 검색한 부분이 저장되도록 하는 로직 구현
최근 검색어가 5개까지만 나타내고 가장 오래된 검색어는 삭제하도록 구현

### Key Changes 🔥 (주요 구현/변경 사항)
UserDefaults 를 Extension 으로 빼서 구현했습니다.
SearchStateHolder 에 최근 검색어 담을 배열과 검색 내용 변수를 선언 후에
5개 이상인지 검사하고 삭제 및 추가 하는 updateSearchHistorys() 로직을 구현 했습니다.
검색 내용 변수를 초기화해주는 initializeSearchContent() 로직을 구현했습니다.

### ScreenShot 📷 (참고 사진)

https://user-images.githubusercontent.com/103012087/192139054-626e5aa2-31fa-4fac-a346-0c76f87c7181.MP4

### ToDo 📆 (남은 작업)
- [ ] 삭제 로직 구현

### Close Issues 🔒 (닫을 Issue)
Close #19 

### To Reviewers 🙏 (리뷰어에게 전달하고 싶은 말)
- 최근 검색어 정렬이 가장 최근 검색어가 하단으로 내려오도록 우선 구현했는데 리버스 시켜서 상단으로 위치하도록 하는게 나을지 리뷰 부탁드립니다.
- UserDefaults 말고 더 좋은 저장 방법이 있다면 리뷰 부탁드립니다.
- UserDefaults를 Extension 으로 빼는 것보다 더 좋은 방법 있다면 리뷰 부탁드립니다.
- PR 양 최대한 적고 적당하게 잡았는데 혹시 개선사항 있다면 리뷰 부탁드립니다.

2022-09-29 11:33 UTC, feldblume5263 commented on Module-MeetUP/Module-MeetUP/App/Module_MeetUPApp.swift
>          }
이 부분 원래대로 하는거 깜빡 하셨군요.

2022-09-29 11:35 UTC, feldblume5263 commented on Module-MeetUP/Module-MeetUP/Global/Extension/UserDefaultsExtension.swift
> +            array(forKey: "isSearchHistorys") as? [String] ?? []
UserDefaults의 key값이 isSearchHistroys인 것은 부자연스러운 것 같습니다.
is 가 앞에 붙는 다는 것은 Bool 값을 보통 의미하는데, String 값을 가지네요.
검색 이력을 저장하는 것 같은데 더 적절한 key값이 필요할 듯 합니다.

2022-09-29 11:36 UTC, feldblume5263 commented on Module-MeetUP/Module-MeetUP/Screens/PostsListView/PostsListViewComponents/PostCellView.swift
>                  .foregroundColor(.gray)
해당 줄을 제거하신 이유가 ios 16부터 지원되는 문제 때문인가요?
이전에 font weight를 설정하는 다른 방법이 있는 것으로 알고 있습니다.

2022-09-29 11:37 UTC, TaekH commented on Module-MeetUP/Module-MeetUP/App/Module_MeetUPApp.swift
>          }
😓 빠르게 수정하겠습니다..

2022-09-29 11:37 UTC, feldblume5263 commented on Module-MeetUP/Module-MeetUP/Screens/Search/SearchStateHolder.swift
> +        didSet {
혹시 해당 변수를 didSet으로 이용하시는 이유가 무엇일까요?
userdefault를 사용하고 싶으신거라면 @AppStorage를 고려해보셨나요?

2022-09-29 11:41 UTC, feldblume5263 commented on Module-MeetUP/Module-MeetUP/Screens/Search/SearchStateHolder.swift
> +        if searchHistorys.count > 4 {
이 부분은 함수로 만들기 보다는 오히려 searchHistory 함수를 property wrapper로 따로 감싸서 만드는 것이 더 깔끔할 것 같습니다.
그렇게 하면 변수가 어떤 규칙을 가지고 있는지 바로 알수 있고, 나중에 해당 저장 규칙을 수정할 때 변수에만 집중하면 되서 더 좋을 것 같아요

2022-09-29 11:43 UTC, feldblume5263 commented on Module-MeetUP/Module-MeetUP/Screens/Search/SearchView.swift
> +    @ObservedObject var searchStates: SearchStateHolder
현재 ObservedObject가 선언되어 있고 이를 RecentSearchHistoryListView 에서 stateObject로 받아서 사용하는데 그렇게 하신 이유가 있으실까요?

2022-09-29 11:45 UTC, feldblume5263 commented on Module-MeetUP/Module-MeetUP/Screens/Search/SearchViewComponents/RecentSearchHistoryListView.swift
>  struct RecentSearchHistoryCellView: View {
Cell은 그 자체로 view를 의미하는 경우가 많아서 뒤가 cell로 끝나는 경우가 많은 것 같아요.
아마 UIKit에서부터 그렇게 써왔어서 그게 더 익숙한 것 같습니다.

2022-09-29 11:48 UTC, TaekH commented on Module-MeetUP/Module-MeetUP/Screens/Search/SearchStateHolder.swift
> +        didSet {
@AppStorage를 생각해 보지는 않았던 것 같아요 
SwiftUI 니깐 @AppStorage를 사용하는 방법이 더 간단할거같아요!

2022-09-29 11:48 UTC, TaekH commented on Module-MeetUP/Module-MeetUP/Screens/Search/SearchViewComponents/RecentSearchHistoryListView.swift
>  struct RecentSearchHistoryCellView: View {
넵 RecentSearchHistoryCell 로 수정할게요!

2022-09-29 11:49 UTC, feldblume5263 commented on Module-MeetUP/Module-MeetUP/Screens/Search/SearchViewComponents/SearchBarView.swift
> +    @StateObject var searchStates: SearchStateHolder
이 부분이 왜 stateobject로 받아지는 걸까요?

2022-09-29 11:49 UTC, feldblume5263 commented on Module-MeetUP/Module-MeetUP/Screens/Search/SearchViewComponents/RecentSearchHistoryListView.swift
> +    @StateObject var searchStates: SearchStateHolder
이 부분도 stateobject로 받아질 필요가 없을 것 같아요

2022-09-29 11:53 UTC, feldblume5263 commented on Module-MeetUP/Module-MeetUP/Screens/Search/SearchViewComponents/SearchBarView.swift
> +                searchStates.updateSearchHistorys()
위에서 말씀드린 것처럼 update함수에서 계산 로직이 변수 프로퍼티래퍼로 빠진다면, update 자체에서는 append와 initailize를 함께 하나의 함수에서 해줘도 될 것 같습니다.

2022-09-29 11:57 UTC, feldblume5263 requested changes
리뷰가 늦어서 죄송합니다 🥲
해당 부분 수정하셔서 다시 리뷰 요청 부탁드립니다!

2022-09-29 12:06 UTC, TaekH commented on Module-MeetUP/Module-MeetUP/Screens/Search/SearchView.swift
> +    @ObservedObject var searchStates: SearchStateHolder
이 부분은 StateObject가 부모뷰에 선언되고 자식뷰가 ObservedObject로 선언되어 자식뷰가 부모뷰의 라이프사이클을 따르도록 하는게 맞겠네요..
수정하겠습니다!

2022-10-03 06:55 UTC, TaekH commented on Module-MeetUP/Module-MeetUP/Screens/PostsListView/PostsListViewComponents/PostCellView.swift
>                  .foregroundColor(.gray)
디자인 변경으로 인해 삭제했습니다!
추후에 따로 굵기 다시 적용할 예정입니다

2022-10-03 06:55 UTC, TaekH commented on Module-MeetUP/Module-MeetUP/Screens/Search/SearchViewComponents/SearchBarView.swift
> +    @StateObject var searchStates: SearchStateHolder
https://github.com/ADAM-2022/Module-MeetUp/pull/20#discussion_r983457909 과 동일한 문제로 수정했습니다!

2022-10-03 06:56 UTC, TaekH commented on Module-MeetUP/Module-MeetUP/Screens/Search/SearchViewComponents/RecentSearchHistoryListView.swift
> +    @StateObject var searchStates: SearchStateHolder
https://github.com/ADAM-2022/Module-MeetUp/pull/20#discussion_r983457909 과 동일한 문제로 수정했습니다!

2022-10-03 07:18 UTC, TaekH commented on Module-MeetUP/Module-MeetUP/Screens/Search/SearchStateHolder.swift
> +        didSet {
https://stackoverflow.com/questions/67368023/storing-arrays-of-string-persistently-in-swiftui-using-appstorage
여기서의 답변에는 @AppStorage 를 사용하여 배열을 저장하려는 경우 다른 인코딩/디코딩( Data 타입으로 변환 등 )을 사용하거나 사용자가 직접 지정한 속성래퍼를 사용해야한다고 하는데 차라리 기존에 만들어 두었던 UserDefaults 를 사용하는 것이 더 낫지 않을까요?

2022-10-03 08:35 UTC, TaekH commented on Module-MeetUP/Module-MeetUP/Screens/Search/SearchStateHolder.swift
> +        if searchHistorys.count > 4 {
연산 프로퍼티를 말씀하시는 거겠죠?

2022-10-03 09:11 UTC, TaekH commented
리뷰 결과 나온 수정 부분들 [be8423c](https://github.com/ADAM-2022/Module-MeetUp/pull/20/commits/be8423c3bf9d415d8c556ff6ded3df1f144b727b)에서 수정하였습니다!
다시 리뷰 요청 드립니다!

2022-10-03 09:12 UTC, TaekH commented on Module-MeetUP/Module-MeetUP/Screens/Search/SearchViewComponents/SearchBarView.swift
> +                searchStates.updateSearchHistorys()
[be8423c](https://github.com/ADAM-2022/Module-MeetUp/pull/20/commits/be8423c3bf9d415d8c556ff6ded3df1f144b727b)
에서 수정하였습니다!

2022-10-08 06:56 UTC, TaekH commented on Module-MeetUP/Module-MeetUP/Screens/Search/SearchViewComponents/SearchBarView.swift
> +                searchStates.updateSearchHistorys()
지금 생각해보니append 와 검색창 초기화 함수는 성격이 조금 다른 것 같은데 하나의 함수로 묶어도 괜찮을까요?

2022-10-09 09:40 UTC, feldblume5263 commented on Module-MeetUP/Module-MeetUP/Global/Extension/ArrayExtension.swift
> +//MARK: https://stackoverflow.com/questions/63166706/how-to-store-nested-arrays-in-appstorage-for-swiftui 참고
해당 링크 확인했습니다.

2022-10-09 09:40 UTC, feldblume5263 commented on Module-MeetUP/Module-MeetUP/Global/Extension/UserDefaultsExtension.swift
> +            array(forKey: "isSearchHistorys") as? [String] ?? []
아직 해당 변수명이 고쳐지지 않은 것 같아요!

2022-10-09 09:42 UTC, feldblume5263 commented on Module-MeetUP/Module-MeetUP/Screens/Search/SearchStateHolder.swift
> +                _searchHistorys.remove(at: 0)
이 부분 확인했습니다. 로직적으로 문제가 없어보입니다.

2022-10-09 09:42 UTC, feldblume5263 requested changes
userdefaults 변수명 수정 부탁드립니다!

2022-10-14 08:20 UTC, TaekH commented on Module-MeetUP/Module-MeetUP/Global/Extension/UserDefaultsExtension.swift
> +            array(forKey: "isSearchHistorys") as? [String] ?? []
> userdefaults 변수명 수정 부탁드립니다!

해당 @AppStorage 를 사용하면서 해당 extension 은 삭제했습니다!

2022-10-14 08:27 UTC, feldblume5263 commented on Module-MeetUP/Module-MeetUP/Screens/Search/SearchViewComponents/SearchBarView.swift
> +                searchStates.updateSearchHistorys()
하나의 함수에서 묶어서 작동하지만 함수 내부에서는 개별로 다른 함수들이 사용 되어야 할 것 같습니다!

2022-10-14 08:34 UTC, TaekH commented on Module-MeetUP/Module-MeetUP/Global/Extension/UserDefaultsExtension.swift
> +            array(forKey: "isSearchHistorys") as? [String] ?? []
삭제가 정상적으로 되지 않았네요 다시 삭제 했습니다!

2022-10-15 06:51 UTC, feldblume5263 approved these changes
LGTM 수고하셨어요!

2022-10-15 06:51 UTC, merged