전체 게시글 타이틀 UI 변경
ADAM-2022/Module-MeetUp pull request #22
Opened 2022-10-08 08:12 UTC by TaekH

### Motivation 🥳 (코드를 추가/변경하게 된 이유)
기존 디자인에서 검색바와 글쓰기 버튼이 추가된 타이틀로 변경

### Key Changes 🔥 (주요 구현/변경 사항)
전체게시글에 들어갈 검색바 UI와 글쓰기 버튼 UI 구현

### ScreenShot 📷 (참고 사진)
<image width=300 src="https://user-images.githubusercontent.com/103012087/194697204-038bd4a6-2967-4007-a47e-aaf3baf44883.png">

### ToDo 📆 (남은 작업)
- [ ] 인기 게시글 섹션 삭제
- [ ] 검색 UI 와 연결
- [ ] 스크롤 시 타이틀 그림자 적용
- [ ] 커스텀 색상 추가

### Close Issues 🔒 (닫을 Issue)
Close #21 

### To Reviewers 🙏 (리뷰어에게 전달하고 싶은 말)
- 검색바는 카카오맵 등의 다른 레퍼런스를 참고했을 때 Button이나 TextField 보다 onTapGesture로 검색뷰가 올라오도록 하는 것이 자연스러울 것 같아서 onTapGesture를 넣어두었습니다. 다른 방식이 낫다면 리뷰 부탁드려요!

https://user-images.githubusercontent.com/103012087/194697358-06aad636-da38-4cdb-adf7-78c184f9fcf5.MP4

2022-10-09 09:43 UTC, feldblume5263 commented on Module-MeetUP/Module-MeetUP/Screens/PostsListView/PostsListView.swift
> +            RefreshableScrollView(onRefresh: { refrashDone in
refrashDone은 refresh의 오타일까요?

2022-10-09 09:46 UTC, feldblume5263 requested changes
UI 로직이 깔끔합니다 LGTM!  refrash라는 변수명과 함수명만 한번 확인 부탁드립니다!

2022-10-09 09:47 UTC, feldblume5263 commented
textView가 아닌 onTapGesture로 쓴 부분 좋은 것 같습니다.

2022-10-14 08:46 UTC, TaekH commented on Module-MeetUP/Module-MeetUP/Screens/PostsListView/PostsListView.swift
> +            RefreshableScrollView(onRefresh: { refrashDone in
refresh 가 끝났을 때 로딩 표시가 사라지도록하는 함수입니다!
바꾸는게 나을까요?

2022-10-15 07:49 UTC, feldblume5263 commented on Module-MeetUP/Module-MeetUP/Screens/PostsListView/PostsListView.swift
> +            RefreshableScrollView(onRefresh: { refrashDone in
refresh를 refrash로 오타를 내신게 아닌가 싶어서 남겼습니다!

2022-10-16 02:58 UTC, TaekH commented on Module-MeetUP/Module-MeetUP/Screens/PostsListView/PostsListView.swift
> +            RefreshableScrollView(onRefresh: { refrashDone in
아 오타에요!😓 수정하겠습니다 ..!

2022-10-16 08:39 UTC, TaekH commented on Module-MeetUP/Module-MeetUP/Screens/PostsListView/PostsListView.swift
> +            RefreshableScrollView(onRefresh: { refrashDone in
43e3d0bb9e01ea46724cbe600d87f0337c45149f 에서 수정완료입니다!

2022-10-19 13:21 UTC, feldblume5263 approved these changes
확인했습니다! LGTM!!

2022-10-19 13:22 UTC, merged